### ISSUE TITLE
Support merge file list

### ISSUE THREAD

**Issue by sklee0913** [fvutils/pyucis#24]
and seems that it only supports input as file name, I try to put a list of files but doesn't work.

~/work/regression$ pyucis merge -o merge.xml merge.lists
Traceback (most recent call last):
File "/home/xxx/.local/lib/python3.10/site-packages/ucis/cmd/cmd_merge.py", line 32, in merge
db = db_if.read(input)
File "/home/xxx/.local/lib/python3.10/site-packages/ucis/xml/db_format_if_xml.py", line 19, in read
return XmlFactory.read(file_or_filename)
File "/home/xxx/.local/lib/python3.10/site-packages/ucis/xml/xml_factory.py", line 67, in read
raise e
File "/home/xxx/.local/lib/python3.10/site-packages/ucis/xml/xml_factory.py", line 63, in read
validate_ucis_xml(fp)
File "/home/xxx/.local/lib/python3.10/site-packages/ucis/xml/init.py", line 49, in validate_ucis_xml
doc = etree.parse(fp)
File "src/lxml/etree.pyx", line 3589, in lxml.etree.parse
File "src/lxml/parser.pxi", line 1979, in lxml.etree._parseDocument
File "src/lxml/parser.pxi", line 1999, in lxml.etree._parseFilelikeDocument
File "src/lxml/parser.pxi", line 1893, in lxml.etree._parseDocFromFilelike
File "src/lxml/parser.pxi", line 1224, in lxml.etree._BaseParser._parseDocFromFilelike
File "src/lxml/parser.pxi", line 633, in lxml.etree._ParserContext._handleParseResultDoc
File "src/lxml/parser.pxi", line 743, in lxml.etree._handleParseResult
File "src/lxml/parser.pxi", line 672, in lxml.etree._raiseParseError
File "/home/xxx/work/regression/merge.lists", line 1
lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1

**Comment by sklee0913** [comment]
work around: pyucis merge $(cat merge.lists) -o merge.xml
